# Generated by Django 4.2.22 on 2025-07-12 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillswap_APP', '0002_profile_skillswaprequest_delete_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillswaprequest',
            options={'ordering': ['-timestamp']},
        ),
    ]
