# Generated by Django 4.2.22 on 2025-07-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillswap_APP', '0003_alter_skillswaprequest_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='availability',
            field=models.CharField(default='Weekends', help_text="When you're available to swap skills", max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default-avatar.png', upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills_offered',
            field=models.TextField(blank=True, help_text='Comma-separated list of offered skills'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills_wanted',
            field=models.TextField(blank=True, help_text='Comma-separated list of wanted skills'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='visibility',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', help_text='Control who can see your profile', max_length=10),
        ),
    ]
